import * as THREE from 'three';
import { Enemy, ENEMY_TYPES } from './enemy.js';
import { ITEMS } from './items.js';
import { NPC } from './npc.js';

const V = new THREE.Vector3();

const weaponSpecs = [
 ['steel_sword','Espada de Aço','weapon',['knight'],9,15,160],['heavy_axe','Machado Pesado','weapon',['knight'],12,20,210],['iron_spear','Lança de Ferro','weapon',['knight','paladin'],8,14,180],['shadow_dagger','Adaga Sombria','weapon',['monk','paladin'],7,12,190],['longbow','Arco Longo','weapon',['paladin'],10,16,200],['heavy_crossbow','Besta Pesada','weapon',['paladin'],14,22,260],['ice_staff','Cajado de Gelo','weapon',['sorcerer'],10,17,230],['fire_staff','Cajado de Fogo','weapon',['sorcerer'],11,18,240],['shadow_staff','Cajado Sombrio','weapon',['druid','sorcerer'],12,19,270],['legendary_vocation_weapon','Arma Lendária','weapon',['knight','paladin','sorcerer','druid','monk'],18,28,520]
];
const armorSpecs = [
 ['steel_armor','Armadura de Aço','armor',28,.035,260],['hunter_armor','Armadura do Caçador','armor',20,.025,230],['arcane_robe','Manto Arcano','armor',18,.018,240],['black_knight_armor','Armadura do Cavaleiro Negro','armor',42,.055,420],['elemental_armor','Armadura Elemental','armor',34,.04,390],['speed_boots','Botas da Velocidade','boots',8,0,300],['vanguard_helmet','Elmo do Bastião','head',14,.018,220],['vocation_amulet','Amuleto da Vocação','amulet',20,.012,260],['unique_ring','Anel de Efeito Único','ring',12,.008,280],['legendary_armor','Armadura Lendária','armor',55,.07,650]
];
const consumableSpecs = [
 ['speed_potion','Poção de Velocidade','speed',.2,70],['resistance_potion','Poção de Resistência','resist',.15,75],['crit_potion','Poção de Crítico','crit',.15,90],['magic_potion','Poção de Poder Mágico','magic',.18,95],['defense_potion','Poção de Defesa','defense',.12,80],['regen_potion','Poção de Regeneração','regen',.2,85],['rare_elixir','Elixir Raro','elixir',.5,180],['regional_ore','Minério Regional','material',1,35],['boss_heart','Coração de Boss','material',1,160],['arcane_shard','Fragmento Arcano','material',1,120]
];
for(const [id,name,slot,vocs,a,b,value] of weaponSpecs) ITEMS[id] ||= {id,sprite:'',name,description:'Equipamento avançado de '+name.toLowerCase()+'.',category:'equipamento',maxStack:1,value,equipment:{slot,vocations:vocs},stats:{attackMin:a,attackMax:b},icon:'⚔'};
for(const [id,name,slot,hp,armor,value] of armorSpecs){const stats={maxHp:hp,armorPercent:armor};if(slot==='boots')stats.speed=.12;if(slot==='amulet'){stats.abilityMin=4;stats.abilityMax=7;}if(slot==='ring'){stats.abilityMin=5;stats.abilityMax=8;}ITEMS[id] ||= {id,sprite:'',name,description:'Peça de equipamento avançada: '+name+'.',category:'equipamento',maxStack:1,value,equipment:{slot},stats,icon:'◆'};}
for(const [id,name,type,value,price] of consumableSpecs){const effect=type==='speed'?{type:'buff',buff:'speed',value}:type==='resist'?{type:'buff',buff:'resistance',value}:type==='crit'?{type:'buff',buff:'crit',value}:type==='magic'?{type:'buff',buff:'magic',value}:type==='defense'?{type:'buff',buff:'defense',value}:type==='regen'?{type:'buff',buff:'regen',value}:type==='elixir'?{type:'restoreManaPercent',value:.5}:null;ITEMS[id] ||= {id,sprite:'',name,description:'Recurso da expansão: '+name+'.',category:type==='material'?'material':'consumível',maxStack:type==='material'?50:10,value:price,icon:type==='material'?'◇':'◆',...(effect?{effect}:{})};}

const mobSpecs=[
 ['goblin_miner','Goblin Mineiro',120,3.4,48,16,0x6d8050],['goblin_archer','Arqueiro Goblin',90,3.7,52,20,0x7d6849],['goblin_shaman','Xamã Goblin',105,2.8,65,24,0x75649a],['poison_spider','Aranha Venenosa',88,4,44,18,0x4e7b51],['giant_bat','Morcego Gigante',100,4.6,50,18,0x4b4b67],['skeleton_warrior','Guerreiro Esqueleto',145,2.9,58,20,0xaaa18a],['skeleton_archer','Arqueiro Esqueleto',105,3.4,62,23,0x98917e],['corrupted_zombie','Zumbi Corrompido',170,2.5,75,25,0x4b6348],['dark_wolf','Lobo Sombrio',130,4.5,70,22,0x30333f],['forest_bear','Urso da Floresta',230,2.5,92,28,0x674b35],['slime','Slime',110,2.6,42,14,0x55a873],['acid_slime','Slime Ácido',135,2.4,62,18,0x8aaa43],['cultist','Cultista',155,3,72,25,0x513d58],['arcane_cultist','Cultista Arcano',140,2.7,88,31,0x7351a5],['stone_golem','Golem de Pedra',360,1.8,120,35,0x77736a],['iron_golem','Golem de Ferro',480,1.7,150,42,0x60666e],['fire_elemental','Elemental de Fogo',220,3.2,100,32,0xb75d32],['ice_elemental','Elemental de Gelo',220,3,100,32,0x5e91b4],['ghost','Fantasma',125,3.8,70,30,0xb5b4d0],['cursed_knight','Cavaleiro Amaldiçoado',310,2.9,115,38,0x40364b]
];
for(const [id,name,hp,speed,xp,gold,color] of mobSpecs) ENEMY_TYPES[id] ||= {name,hp,speed,resistances:{physical:.03,magic:.03},rewards:{xp,gold},loot:[{itemId:'regional_ore',chance:.22,min:1,max:2}],aggro:9,range:1.55,damage:[Math.round(hp*.08),Math.round(hp*.11)],windup:.5,cooldown:1.6,radius:.52,height:2,knock:4,expansionColor:color};

export const MAPS=[
 {id:'map4',name:'Floresta Corrompida',color:0x263d28,boss:'corrupted_forest',mobs:['dark_wolf','poison_spider','corrupted_zombie'],features:['atalhos secretos','passagens com quest','cavernas ocultas','áreas de alto risco','pontos de interesse','mudança visual por progresso']},
 {id:'map5',name:'Cidade Antiga',color:0x514b55,boss:'ancient_city',mobs:['goblin_archer','cultist','skeleton_warrior'],features:['torre multiandar','puzzle ambiental','portões com chave','ponte reparável','NPCs de cidade']},
 {id:'map6',name:'Pântano de Nhal',color:0x354a38,boss:'swamp_lord',mobs:['slime','acid_slime','giant_bat'],features:['cavernas secretas','eventos aleatórios','atalhos','materiais regionais']},
 {id:'map7',name:'Fortaleza dos Mortos',color:0x36343c,boss:'fortress_revenant',mobs:['skeleton_warrior','skeleton_archer','cursed_knight'],features:['portões trancados','torre vertical','salas de risco','NPC de recompensa']},
 {id:'map8',name:'Deserto Escarlate',color:0x6d4a32,boss:'desert_titan',mobs:['goblin_miner','fire_elemental','stone_golem'],features:['elevadores','ponte quebrável','minas','evento de tempestade']},
 {id:'map9',name:'Templo Subterrâneo',color:0x303447,boss:'temple_oracle',mobs:['arcane_cultist','ghost','ice_elemental'],features:['puzzles','runas','salas secretas','chaves','lore']},
 {id:'map10',name:'Vulcão do Fim',color:0x4b2721,boss:'final_overlord',mobs:['fire_elemental','iron_golem','cursed_knight'],features:['região final','endgame repetível','boss secreto','equipamentos lendários','eventos']}
];
const bossSpecs=[['corrupted_forest','Guardião da Corrupção',900,90,1200,0x5d8a4a],['ancient_city','Rei das Ruínas',1100,105,1400,0x8a6b54],['swamp_lord','Senhor do Pântano',1250,115,1550,0x547d4c],['fortress_revenant','Revenante da Fortaleza',1500,130,1800,0x62546f],['desert_titan','Titã Escarlate',1750,145,2100,0xa45e32],['temple_oracle','Oráculo Abissal',1950,165,2400,0x5e67a8],['final_overlord','Soberano do Vulcão',2600,220,3500,0xb94b31],['secret_boss','O Devorador Oculto',3200,280,5000,0x713c78],['guardian_duo','Gêmeos do Portão',2200,190,3000,0x596b87],['endless_champion','Campeão do Fim',4000,320,7000,0x9b7b3d]];
export const BOSSES=Object.fromEntries(bossSpecs.map(s=>[s[0],{id:s[0],name:s[1],hp:s[2],xp:s[3],gold:s[4],color:s[5]}]));
export const NPCS=['Ferreiro de Aço','Alquimista','Mercador de Equipamentos','Mestre de Missões','Cronista','Treinador','Comerciante de Materiais','Mestre de Recompensas','Taverneiro','Mestre de Aprimoramentos'].map((name,i)=>({id:'npc_'+(i+1),name,lines:[name+': a estrada adiante guarda uma nova ameaça.','Tenho informações para quem explora as fronteiras.']}));
export const QUESTS=Array.from({length:10},(_,i)=>({id:'exp_quest_'+(i+1),name:['Primeira Expedição','Madeira Corrompida','As Ruínas','Águas Mortas','A Fortaleza','Areias Vermelhas','O Templo','A Última Forja','Caçada Secreta','Fim do Mundo'][i],goal:i<9?'Derrote '+(5+i*3)+' inimigos da expansão.':'Derrote o Campeão do Fim.',target:i<9?5+i*3:1}));
export const ACHIEVEMENTS=['Primeiro passo','Explorador das fronteiras','Caçador de Goblins','Predador do pântano','Quebrador de fortalezas','Senhor das areias','Desvendador do templo','Mestre da forja','Caçador secreto','Fim do Fim'].map((name,i)=>({id:'achievement_'+(i+1),name,goal:i+1}));
export const LORE=MAPS.map((m,i)=>({id:'lore_'+(i+4),title:'Crônicas de '+m.name,text:'Os mapas antigos registram '+m.name+' como uma fronteira onde o passado ainda influencia o presente. Cada expedição revela novas pistas.'}));
export const RECIPES=weaponSpecs.slice(0,5).map((s,i)=>({id:'recipe_'+(i+1),name:s[1],result:s[0],materials:{regional_ore:3+i,boss_heart:i}}));

class ExpansionBoss extends Enemy{
 constructor(game,spec,x,z){const type='__boss_'+spec.id;ENEMY_TYPES[type] ||= {name:spec.name,hp:spec.hp,speed:2.2,resistances:{physical:.08,magic:.08},rewards:{xp:spec.xp,gold:spec.gold},loot:[{itemId:'boss_heart',chance:1}],aggro:14,range:2.1,damage:[30,44],windup:.65,cooldown:1.4,radius:1.25,height:2.8,knock:2,expansionColor:spec.color};super(game,type,x,z);this.isBoss=true;this.name=spec.name;this.spec=spec;this.phase=1;this.maxHp=spec.hp;this.hp=spec.hp;this.barT=9999;this.root.scale.setScalar(1.65);this.root.traverse(o=>{if(o.isMesh&&o.material?.color){o.material.color.setHex(spec.color);o.material.emissive?.setHex(spec.color);o.material.emissiveIntensity=.25;}});}
 takeDamage(n,from,crit){if(!this.alive)return;const before=this.hp;super.takeDamage(n,from,crit);if(this.alive&&this.phase===1&&this.hp<=this.maxHp*.5){this.phase=2;this.def.speed*=1.22;this.def.damage=[Math.round(this.def.damage[0]*1.25),Math.round(this.def.damage[1]*1.25)];this.game.ui.banner('FASE 2',this.name+' libera seu poder oculto.','boss',1.8);}if(before>0&&this.hp<=0)this.game.onBossDefeated({xp:this.spec.xp,gold:this.spec.gold,loot:[{itemId:'boss_heart',amount:1},{itemId:'regional_ore',amount:5}]},this.pos);}
 die(){if(!this.alive)return;this.alive=false;this.state='dead';this.stateT=0;this.anim?.die();this.game.ui.removeAnchor(this.bar);this.game.fx.emit(V.copy(this.pos).setY(1.5),{count:80,color:this.spec.color,speed:7,up:2,life:1.4,size:.55,drag:2});this.game.area?.onEnemyKilled?.(this);}
}

function addBlock(scene,collision,group,x,z,w,d,color,wall=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,wall?2.8:.18,d),new THREE.MeshStandardMaterial({color,roughness:.9}));m.position.set(x,wall?1.4:-.09,z);m.castShadow=true;m.receiveShadow=true;group.add(m);if(wall)collision.addBox(x-w/2,x+w/2,z-d/2,z+d/2,{projectiles:false});return m;}

function createExpansionArea(game,map){
 const scene=game.scene,collision=game.collision,baseZones=collision.zones.length,baseObs=collision.obstacles.length,baseInt=game.interaction.items.length,root=new THREE.Group();scene.add(root);
 const floor=new THREE.Mesh(new THREE.BoxGeometry(74,.2,74),new THREE.MeshStandardMaterial({color:map.color,roughness:1}));floor.position.set(0,-.1,0);root.add(floor);collision.addRectZone(-36,36,-36,36);
 for(const p of [[0,-35,72,1],[0,35,72,1],[-35,0,1,72],[35,0,1,72]])addBlock(scene,collision,root,p[0],p[1],p[2],p[3],0x24262a,true);
 for(let i=0;i<16;i++){const a=i*Math.PI*2/16,r=9+(i%3)*5,x=Math.cos(a)*r,z=Math.sin(a)*r;addBlock(scene,collision,root,x,z,1.4+(i%2),1.4+(i%3)*.5,0x4a4b43,true);}
 const local=[];map.mobs.forEach((type,idx)=>{for(let j=0;j<3;j++){const e=new Enemy(game,type,-18+idx*10+j*2.5,-14+j*9);e.root.traverse(o=>{if(o.isMesh&&o.material?.color&&ENEMY_TYPES[type].expansionColor)o.material.color.setHex(ENEMY_TYPES[type].expansionColor);});local.push(e);game.addEnemy(e);}});
 const bossSpec=BOSSES[map.boss]||BOSSES.final_overlord,boss=new ExpansionBoss(game,bossSpec,0,25);local.push(boss);game.addEnemy(boss);game.ui.showBoss(boss.name);
 const visuals=[];const pois=[['SEGREDO',-25,-24,0xd17cff],['CHAVE',25,-20,0xffd36a],['PUZZLE',-22,18,0x72c7ff],['LORE',23,16,0xa98cff]];
 for(const [label,x,z,c] of pois){const g=new THREE.Group();g.position.set(x,0,z);const ob=new THREE.Mesh(new THREE.CylinderGeometry(.45,.6,.25,8),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.35}));ob.position.y=.14;g.add(ob);root.add(g);visuals.push(g);game.interaction.add({pos:g.position,radius:2.2,height:1.4,label:'Investigar '+label,onInteract:()=>game.ui.toast(label+': descoberta registrada no Atlas.')});}
 const idx=Number(map.id.slice(-1))-4,n1=NPCS[idx]||NPCS[0],n2=NPCS[(idx+1)%NPCS.length],npc=new NPC(game,{name:n1.name,x:-28,z:-28,dialogue:()=>({lines:n1.lines})}),npc2=new NPC(game,{name:n2.name,x:28,z:-28,dialogue:()=>({lines:n2.lines})});game.npcs.push(npc,npc2);
 return {name:map.name,spawn:{x:0,z:-30,facing:0},checkpoint:{x:0,z:-30,facing:0},boss,onStart(){game.ui.setObjective?.('Explorar '+map.name,'Encontre o guardião da região.');},onEnemyKilled(){},update(){},onRespawn(){},dispose(){for(const e of local){if(game.enemies.includes(e))e.dispose?.();}game.enemies=game.enemies.filter(e=>!local.includes(e));game.npcs=game.npcs.filter(n=>n!==npc&&n!==npc2);scene.remove(npc.root,npc2.root);scene.remove(root);collision.zones.splice(baseZones);collision.obstacles.splice(baseObs);game.interaction.items.splice(baseInt);game.ui.hideBoss();}};
}

function makeOverlay(game){
 let panel=document.getElementById('expansion-atlas');if(panel)return panel;
 panel=document.createElement('div');panel.id='expansion-atlas';panel.style.cssText='position:fixed;inset:8%;z-index:500;background:rgba(7,10,16,.97);border:1px solid #9a7b46;color:#eee;padding:24px;font:14px system-ui;overflow:auto;pointer-events:auto;box-shadow:0 20px 70px #000';
 panel.innerHTML='<button id="exp-close" style="float:right">Fechar</button><h1>Atlas da Expansão</h1><div id="exp-tabs"></div><div id="exp-body"></div>';document.body.appendChild(panel);
 document.getElementById('exp-close').onclick=()=>{panel.classList.add('hidden');if(game.state==='atlas'){game.state='play';game.inputLocked=false;}};
 const tabs=[['mapas','Mapas'],['mobs','Bestiário'],['itens','Itens'],['sistemas','Sistemas'],['lore','Lore']],tabsEl=panel.querySelector('#exp-tabs'),body=panel.querySelector('#exp-body');
 const render=tab=>{body.innerHTML='';if(tab==='mapas')body.innerHTML=MAPS.map(m=>'<h2>'+m.name+'</h2><p>'+m.features.join(' · ')+'</p><p>Boss: '+(BOSSES[m.boss]?.name||m.boss)+'</p><button data-map="'+m.id+'">Entrar na região</button>').join('');if(tab==='mobs')body.innerHTML=mobSpecs.map(m=>'<p><b>'+m[1]+'</b> · HP '+m[2]+' · XP '+m[4]+'</p>').join('');if(tab==='itens')body.innerHTML=Object.values(ITEMS).filter(i=>i.value>=150).map(i=>'<p><b>'+i.name+'</b> · '+i.category+' · '+i.value+' ouro</p>').join('');if(tab==='sistemas')body.innerHTML='<p>Quest journal · Achievements · Bestiary · Lore Codex · Crafting · Equipment upgrades · Rare drops · Random events · Repeatable endgame.</p><p>Os pontos de interesse das regiões cobrem atalhos, chaves, salas secretas, puzzles, pontes, torres e progressão visual.</p>';if(tab==='lore')body.innerHTML=LORE.map(l=>'<h3>'+l.title+'</h3><p>'+l.text+'</p>').join('');};
 body.onclick=e=>{const id=e.target?.dataset?.map;if(id){panel.classList.add('hidden');game.state='play';game.inputLocked=false;game.enterExpansionMap(id);}};
 for(const [id,label] of tabs){const b=document.createElement('button');b.textContent=label;b.onclick=()=>render(id);b.style.margin='4px';tabsEl.appendChild(b);}render('mapas');panel.classList.add('hidden');return panel;
}

export function installExpansion(game){
 game.expansion={maps:MAPS,mobs:mobSpecs,bosses:BOSSES,npcs:NPCS,quests:QUESTS,achievements:ACHIEVEMENTS,lore:LORE,recipes:RECIPES,items:Object.keys(ITEMS)};
 const atlas=makeOverlay(game);
 game.openExpansionAtlas=()=>{atlas.classList.remove('hidden');game.state='atlas';game.inputLocked=true;};
 game.enterExpansionMap=id=>{if(game.state!=='play'||game.inputLocked)return;const map=MAPS.find(m=>m.id===id);if(!map)return;game.returnArea=game.area;game.returnEnemies=game.enemies;game.enemies=[];game.inputLocked=true;game.ui.fade(true);game.schedule(.7,()=>{game.area=createExpansionArea(game,map);game.player.place(0,-30,0);game.rig.snap(game.player.pos);game.area.onStart();});game.schedule(1.4,()=>{game.ui.fade(false);game.inputLocked=false;});};
 addEventListener('keydown',e=>{if(e.code==='KeyO'&&game.state==='play'){e.preventDefault();game.openExpansionAtlas();}});
 const oldKilled=game.onEnemyKilled.bind(game);game.onEnemyKilled=(enemy,loot=[])=>{if(game.expansion&&enemy?.type&&!enemy.isBoss)game.expansion.kills=(game.expansion.kills||0)+1;return oldKilled(enemy,loot);};
 game.craftExpansionItem=recipeId=>{const r=RECIPES.find(x=>x.id===recipeId);if(!r||!game.character)return false;for(const [id,n] of Object.entries(r.materials))if(game.character.getItemCount(id)<n)return false;for(const [id,n] of Object.entries(r.materials))game.character.removeItem(id,n);const result=game.character.addItem(r.result,1,ITEMS[r.result]?.maxStack||1);if(!result.added)return false;game.ui.setInventory(game.character);game.ui.toast('Fabricado: '+(ITEMS[r.result]?.name||r.result));return true;};
 game.upgradeExpansionEquipment=itemId=>{const item=ITEMS[itemId];if(!item?.stats||!game.character)return false;const cost=60+Math.floor((item.value||100)*.15);if(game.character.gold<cost)return false;game.character.spendGold(cost);item.stats={...item.stats,maxHp:(item.stats.maxHp||0)+3};game.ui.toast('Aprimorado: '+item.name);game.ui.setInventory(game.character);return true;};
}